### ISSUE TITLE
[Feature]: Semantic versioning

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [wireghoul/graudit#68]
This repository doesn't use [semantic versioning](https://semver.org/). It really should, as that would allow graudit to exist in package managers so it can be updated more easily.

For example: `3.5` would become `3.5.0`

**Comment by wireghoul** [comment]
Sorry, but I have no desire to support distro packages. The recommended install path is to clone the repo. That way the users get all the extra bits like the scripts located in the misc directory and can pull in new rules when they are available rather than waiting 6 months for the version to get bumped.
