### ISSUE TITLE
trouble parsing graudit.7

### ISSUE THREAD

**Issue by alexmyczko** [wireghoul/graudit#70]
**Describe the bug**
ECANTPARSEGRAUDIT.7

**To Reproduce**
1. Run `man 7 graudit`

**Expected behavior**
Show something more useful

**Actual behavior**
It says iblahblahblahblah blahblhablhablhablhablhab

**Debugging**
not applicable

**Please complete the following information**
 - OS: Debian GNU/Linux sid+experimental
 - 3.6
 - https://ftp-master.debian.org/new/graudit_3.6-1.html

**Comment by wireghoul** [comment]
Oh yes, sorry the man pages were never completed. I've become partial to got clone and pull so the rules stay updated as I often push many small updates and releases can be years apart. I understand that this could be seen as a supply chain risk, but I have little incentive to maintain package support. I'll leave this open for a while in case anyone wants to contribute documentation otherwise I'll remove the man files from the Makefile in the future.

**Comment by bcoles** [comment]
Here is a lazily-written incomplete valid man page to replace the existing corrupt man pages.

![man -l graudit.in.7](https://github.com/user-attachments/assets/b6c91ccb-dc0f-471a-8213-4fa2eaa5a0e5)

```diff
diff --git a/graudit.in.7 b/graudit.in.7
index 6a3cf98..035f908 100644
--- a/graudit.in.7
+++ b/graudit.in.7
@@ -4,7 +4,7 @@
 .\" See mdoc(7) for further reference.
 .\"
 .Dd $Mdocdate: June 3 2010 $
-.Dt MANUALS 7
+.Dt GRAUDIT 7
 .Os
 .Sh NAME
 .\"
@@ -15,5 +15,13 @@
 .\"
 .Em graudit is only as good as the signature database.
 .Pp
-iblahblahblahblah
-blahblhablhablhablhablhab
+.Sh "FORMAT"
+.\"
+.sp
+Signature database files are stored in the `signatures` directory.
+These files contain one signature per line.
+Each signature consists of a grep-compatible regex.
+.\"
+.Pp
+.Sh SEE ALSO
+.Xr grep(1),regex(3)
```
