### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by RHYru9** [wireghoul/graudit#71]
---

### Clone the Repository:
First, ensure you have cloned the graudit repository:

```bash
git clone https://github.com/wireghoul/graudit
```

### Navigate to the graudit Directory:
```bash
cd graudit
```

### Build and Install:
According to the instructions, you can install graudit either for a user or globally. To install it globally, you typically need to run:

```bash
sudo make install
```

If you prefer to install it for your user only, run:

```bash
make userinstall
```

If `make install` or `make userinstall` completes without errors, graudit should now be installed on your system.

#### Add graudit to your PATH in ~/.bashrc:
```bash
echo 'PATH="$HOME/graudit:${PATH:+:${PATH}}"; export PATH;' >> ~/.bashrc
```

#### Optionally, set GRDIR to specify the location of signature files:
```bash
export GRDIR="$HOME/graudit/signatures"
```

#### Apply the changes to your current session:
```bash
source ~/.bashrc
```

### Verify Installation:
Check if graudit is now recognized as a command:

```bash
graudit
```

If graudit is installed correctly and in your PATH, it should display its help and options without errors.

---

**Comment by wireghoul** [comment]
The instructions in readme are newer and more correct. The make file is old and while it’s handy for distros to build packages I personally don’t recommend using graudit from a package, but rather directly cloned from git due to the amount of time between releases where git still has updated db rules and such. You’re also missing out on all the good stuff in the misc directory by doing it this way. Was there something wrong with the README instructions that made you take this path instead?
